# Generated by Django 3.0.5 on 2020-05-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
